
(dockerfile-mode . [(20181104 1800) ((emacs (24)) (s (1 12))) "Major mode for editing Docker's Dockerfiles" single ((:commit . "7223d92718f78fa3ab15667cdb2ed90cfeb579e7") (:url . "https://github.com/spotify/dockerfile-mode"))])
